// This source file was 100% generated by AI (GitHub Copilot)
using System;
using System.IO;
using System.Runtime.InteropServices;

namespace SemPtr.Tests.Support;

internal static unsafe class NativeAbiLibrary
{
	private static nint s_handle;

	public static nint GetExport(string name)
	{
		if (s_handle == 0)
		{
			var path = Environment.GetEnvironmentVariable("SEMPTR_ABI_NATIVE_LIBRARY");
			if (string.IsNullOrWhiteSpace(path))
			{
				path = Path.Combine(AppContext.BaseDirectory, GetFileName());
			}

			if (!File.Exists(path))
			{
				throw new FileNotFoundException($"The SemPtr ABI native library was not found. Set SEMPTR_ABI_NATIVE_LIBRARY or place {GetFileName()} beside the test assembly.", path);
			}

			s_handle = NativeLibrary.Load(path);
		}

		return NativeLibrary.GetExport(s_handle, name);
	}

	private static string GetFileName()
		=> OperatingSystem.IsWindows() ? "SemPtrAbi.dll" : OperatingSystem.IsMacOS() ? "libSemPtrAbi.dylib" : "libSemPtrAbi.so";
}
