# This source file was 100% generated by AI (GitHub Copilot)
#!/usr/bin/env bash
set -euo pipefail

output_directory="${1:?output directory is required}"
script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$output_directory"

case "$(uname -s)" in
  Linux) output="$output_directory/libSemPtrAbi.so"; cc -shared -fPIC -O2 -std=c11 -o "$output" "$script_directory/SemPtrAbi.c" ;;
  Darwin) output="$output_directory/libSemPtrAbi.dylib"; clang -dynamiclib -O2 -std=c11 -o "$output" "$script_directory/SemPtrAbi.c" ;;
  *) echo "Unsupported operating system: $(uname -s)" >&2; exit 2 ;;
esac

echo "$output"
