# This source file was 100% generated by AI (GitHub Copilot)
param(
    [Parameter(Mandatory = $true)]
    [string] $OutputDirectory
)

$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$output = Join-Path $OutputDirectory 'SemPtrAbi.dll'
cl.exe /nologo /LD /O2 /TC (Join-Path $PSScriptRoot 'SemPtrAbi.c') /Fe:$output
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Write-Output $output
