// This source file was 100% generated by AI (GitHub Copilot)
#include "SemPtrAbi.h"

void* semptr_abi_identity(void* value)
{
	return value;
}

void* semptr_abi_add_offset(void* value, uintptr_t offset)
{
	return (void*)((unsigned char*)value + offset);
}

void semptr_abi_replace(void** destination, void* replacement)
{
	*destination = replacement;
}

void semptr_abi_write_int(int* destination, int value)
{
	*destination = value;
}
