// This source file was 100% generated by AI (GitHub Copilot)
#ifndef SEMPTR_ABI_H
#define SEMPTR_ABI_H

#include <stdint.h>

#if defined(_WIN32)
#define SEMPTR_ABI_EXPORT __declspec(dllexport)
#else
#define SEMPTR_ABI_EXPORT __attribute__((visibility("default")))
#endif

SEMPTR_ABI_EXPORT void* semptr_abi_identity(void* value);
SEMPTR_ABI_EXPORT void* semptr_abi_add_offset(void* value, uintptr_t offset);
SEMPTR_ABI_EXPORT void semptr_abi_replace(void** destination, void* replacement);
SEMPTR_ABI_EXPORT void semptr_abi_write_int(int* destination, int value);

#endif
