using System;
using System.Runtime.InteropServices;

namespace SemPtr;

/// <summary>
/// Represents an abstract base class for attributes that control the generation of <see langword="extension"/> members for function pointer types.
/// </summary>
public abstract class FunctionPointerExtensionsBaseAttribute : Attribute
{
	/// <summary>
	/// The default name of the <see langword="extension"/> method that will be generated for invoking the function pointer.
	/// </summary>
	public const string DefaultInvokeMethodName = "Invoke";

	/// <summary>
	/// Gets or initializes the type where the <see langword="extension"/> members should be generated.
	/// </summary>
	/// <value>
	/// The type where the <see langword="extension"/> members should be generated, or <c><see langword="null"/></c> to generate them in the default <see langword="extension"/> host type for function pointers.
	/// </value>
	/// <remarks>
	/// <para>
	/// If the value of this property is <c><see langword="null"/></c>, the <see langword="extension"/> members will be generated in the default extensions host type for function pointers,
	/// which is either an <see langword="internal"/> type in the <see langword="global"/> <see langword="namespace"/> or the type in the compilation that is annotated with the <see cref="FunctionPointerDefaultExtensionsAttribute"/> attribute.
	/// </para>
	/// <para>
	/// The type specified in this property must be a valid type for hosting <see langword="extension"/> members (i.e., it must be a top-level <see langword="static"/> <see langword="class"/>)
	/// and it must be declared <see langword="partial"/>. Otherwise, it will result in a compilation error.
	/// </para>
	/// </remarks>
	public Type? ExtensionsHostType { get; init; } = default;

	/// <summary>
	/// Gets or initializes the name of the <see langword="extension"/> method that will be generated for invoking the function pointer.
	/// </summary>
	/// <value>
	/// The name of the method that will be generated for invoking the function pointer.
	/// </value>
	/// <remarks>
	/// <para>
	/// The <see langword="extension"/> method for invoking the function pointer will be generated with the specified name in the type specified by the <see cref="ExtensionsHostType"/> property
	/// (or in the default extensions host type for function pointers if <see cref="ExtensionsHostType"/> is <c><see langword="null"/></c> or not specified).
	/// </para>
	/// <para>
	/// If the value of this property is not specified, the name of the method will default to <see cref="DefaultInvokeMethodName"/> (<c>"Invoke"</c>).
	/// </para>
	/// <para>
	/// The value specified in this property must be a valid C# identifier and can't be neither a reserved keyword nor <c>"Raw"</c> or <c>"FromRaw"</c>.
	/// Otherwise, it will result in a compilation error.
	/// </para>
	/// </remarks>
	public string InvokeMethodName { get; init; } = DefaultInvokeMethodName;

	/// <summary>
	/// Gets or initializes a value indicating whether the <see langword="extension"/> members for creating a function pointer from a raw pointer (<c>FromRaw</c> method)
	/// and for obtaining a raw pointer from a function pointer (<c>Raw</c> property) should be generated.
	/// </summary>
	/// <value>
	/// A value indicating whether the <see langword="extension"/> members for creating a function pointer from a raw pointer (<c>FromRaw</c> method)
	/// and for obtaining a raw pointer from a function pointer (<c>Raw</c> property) should be generated.
	/// </value>
	/// <remarks>
	/// <para>
	/// This property controls whether the <see langword="extension"/> members <c>FromRaw</c> and <c>Raw</c> will generated in the type specified by the <see cref="ExtensionsHostType"/> property
	/// (or in the default extensions host type for function pointers if <see cref="ExtensionsHostType"/> is <c><see langword="null"/></c> or not specified).
	/// </para>
	/// <para>
	/// Note that
	/// </para>
	/// <para>
	/// If the value of this property is not specified, the <see langword="extension"/> members <c>FromRaw</c> and <c>Raw</c> will be generated by default.
	/// </para>
	/// </remarks>
	public bool RawPointerExtensions { get; init; } = true;

	/// <summary>
	/// Gets or initializes the calling conventions that should be used for the generated <see langword="extension"/> members for invoking the function pointer.
	/// </summary>
	/// <value>
	/// The calling conventions that should be used for the generated <see langword="extension"/> members for invoking the function pointer,
	/// or <c><see langword="null"/></c> to use the calling conventions specified by an <see cref="UnmanagedFunctionPointerAttribute"/> on the target <see langword="delegate"/> type,
	/// or the default calling convention for the platform if none is specified.
	/// </value>
	/// <remarks>
	/// <para>
	/// If the value of this property is <c><see langword="null"/></c>, the calling conventions specified by an <see cref="UnmanagedFunctionPointerAttribute"/> on the target <see langword="delegate"/> type will be used,
	/// or the default calling convention for the platform if none is specified.
	/// </para>
	/// <para>
	/// The values specified in this property must be valid calling conventions types (i.e., <c>CallConv*</c> types from the <see cref="System.Runtime.CompilerServices"/> namespace).
	/// </para>
	/// </remarks>
	public Type[]? CallConvs { get; init; } = default;
}
