// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerFormatting</c>: the default (<c>"0x"</c>-prefixed,
	/// architecture-dependent zero-padded hexadecimal) <c>ToString()</c>/<c>ToString(IFormatProvider?)</c> overloads, the
	/// raw (unprefixed) <c>ToString(string?)</c>/<c>ToString(string?, IFormatProvider?)</c> overloads, and the
	/// <see cref="System.ISpanFormattable"/>/<see cref="System.IUtf8SpanFormattable"/> <c>TryFormat</c> overloads
	/// (for both <see langword="char"/> and <see langword="byte"/> destinations), including the "destination too small" case.
	/// </summary>
	private static void GenerateFormattingTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var rawExpr = characteristics.Typeability is Typeability.Typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var className = $"{SafeName(in characteristics)}_FormattingTests";

		AppendTestFileHeader(builder, "using System.Globalization;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void ToString_Default_ReturnsHexPrefixedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = "0x" + ((nuint)raw).ToString(global::SemPtr.Internal.PointerFormat.DefaultFormatString, CultureInfo.InvariantCulture);
					Assert.Equal(expected, pointer.ToString());
				}

				[Fact]
				public unsafe void ToString_WithFormatProvider_ReturnsHexPrefixedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = "0x" + ((nuint)raw).ToString(global::SemPtr.Internal.PointerFormat.DefaultFormatString, CultureInfo.InvariantCulture);
					Assert.Equal(expected, pointer.ToString(CultureInfo.InvariantCulture));
				}

				[Fact]
				public unsafe void ToString_WithFormat_ReturnsUnprefixedFormattedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = ((nuint)raw).ToString("X4", CultureInfo.InvariantCulture);
					Assert.Equal(expected, pointer.ToString("X4"));
				}

				[Fact]
				public unsafe void ToString_WithFormatAndFormatProvider_ReturnsUnprefixedFormattedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = ((nuint)raw).ToString("X4", CultureInfo.InvariantCulture);
					Assert.Equal(expected, pointer.ToString("X4", CultureInfo.InvariantCulture));
				}

				[Fact]
				public unsafe void TryFormat_CharSpan_Default_ReturnsHexPrefixedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = "0x" + ((nuint)raw).ToString(global::SemPtr.Internal.PointerFormat.DefaultFormatString, CultureInfo.InvariantCulture);

					global::System.Span<char> destination = stackalloc char[64];
					var success = pointer.TryFormat(destination, out var charsWritten, CultureInfo.InvariantCulture);

					Assert.True(success);
					Assert.Equal(expected, new string(destination[..charsWritten]));
				}

				[Fact]
				public unsafe void TryFormat_CharSpan_DestinationTooSmall_ReturnsFalse()
				{
					using var buffer = new NativeArray<int>(1);
					var pointer = {{typeName}}.FromRaw({{rawExpr}});

					global::System.Span<char> destination = stackalloc char[1];
					var success = pointer.TryFormat(destination, out var charsWritten);

					Assert.False(success);
					Assert.Equal(0, charsWritten);
				}

				[Fact]
				public unsafe void TryFormat_CharSpan_WithFormat_ReturnsUnprefixedFormattedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = ((nuint)raw).ToString("X4", CultureInfo.InvariantCulture);

					global::System.Span<char> destination = stackalloc char[64];
					var success = pointer.TryFormat(destination, out var charsWritten, "X4", CultureInfo.InvariantCulture);

					Assert.True(success);
					Assert.Equal(expected, new string(destination[..charsWritten]));
				}

				[Fact]
				public unsafe void TryFormat_ByteSpan_Default_ReturnsHexPrefixedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = "0x" + ((nuint)raw).ToString(global::SemPtr.Internal.PointerFormat.DefaultFormatString, CultureInfo.InvariantCulture);

					global::System.Span<byte> destination = stackalloc byte[64];
					var success = pointer.TryFormat(destination, out var bytesWritten, CultureInfo.InvariantCulture);

					Assert.True(success);
					Assert.Equal(expected, global::System.Text.Encoding.UTF8.GetString(destination[..bytesWritten]));
				}

				[Fact]
				public unsafe void TryFormat_ByteSpan_DestinationTooSmall_ReturnsFalse()
				{
					using var buffer = new NativeArray<int>(1);
					var pointer = {{typeName}}.FromRaw({{rawExpr}});

					global::System.Span<byte> destination = stackalloc byte[1];
					var success = pointer.TryFormat(destination, out var bytesWritten);

					Assert.False(success);
					Assert.Equal(0, bytesWritten);
				}

				[Fact]
				public unsafe void TryFormat_ByteSpan_WithFormat_ReturnsUnprefixedFormattedAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromRaw(raw);
					var expected = ((nuint)raw).ToString("X4", CultureInfo.InvariantCulture);

					global::System.Span<byte> destination = stackalloc byte[64];
					var success = pointer.TryFormat(destination, out var bytesWritten, "X4", CultureInfo.InvariantCulture);

					Assert.True(success);
					Assert.Equal(expected, global::System.Text.Encoding.UTF8.GetString(destination[..bytesWritten]));
				}
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Formatting.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
