// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerDeclaration</c>: construction from a raw pointer (including the
	/// non-<see langword="null"/> guard for non-nullable pointer types), the parameterless-constructor/<see langword="default"/>
	/// prohibition for non-nullable pointer types, the <c>Null</c> property for nullable pointer types, <c>FromIntPtr</c>/<c>FromUIntPtr</c>,
	/// <c>ToIntPtr</c>/<c>ToUIntPtr</c>, the <c>Raw</c> property, and the implicit/explicit conversions to and from the raw pointer type.
	/// </summary>
	private static void GenerateDeclarationTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var rawType = RawPointerTypeName(in characteristics);
		var nonNull = characteristics.Nullability is Nullability.NonNull;
		var rawExpr = characteristics.Typeability is Typeability.Typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var className = $"{SafeName(in characteristics)}_DeclarationTests";

		AppendTestFileHeader(builder, "using System;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void Constructor_NonNullRawPointer_SetsRaw()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = new {{typeName}}(raw);
					Assert.Equal((nint)raw, (nint)pointer.Raw);
				}

				[Fact]
				public unsafe void Raw_ReturnsSameAddressAsConstructorArgument()
				{
					using var buffer = new NativeArray<int>(2);
					var raw = {{rawExpr}};
					var pointer = new {{typeName}}(raw);
					Assert.True(pointer.Raw == raw);
				}

			""");

		if (nonNull)
		{
			builder.Append($$"""

					[Fact]
					public unsafe void Constructor_NullRawPointer_ThrowsArgumentNullException()
						=> Assert.Throws<ArgumentNullException>(() => new {{typeName}}(({{rawType}})null));

					[Fact]
					public void FromIntPtr_Zero_ThrowsArgumentNullException()
						=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromIntPtr(nint.Zero));

					[Fact]
					public void FromUIntPtr_Zero_ThrowsArgumentNullException()
						=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromUIntPtr(nuint.Zero));

				""");
		}
		else
		{
			builder.Append($$"""

					[Fact]
					public unsafe void Constructor_NullRawPointer_CreatesNullPointer()
					{
						var pointer = new {{typeName}}(({{rawType}})null);
						Assert.True(pointer.Raw is null);
						Assert.False(pointer.HasTarget);
					}

					[Fact]
					public unsafe void Null_Property_ReturnsNullPointer()
					{
						var pointer = {{typeName}}.Null;
						Assert.True(pointer.Raw is null);
						Assert.False(pointer.HasTarget);
					}

					[Fact]
					public unsafe void FromIntPtr_Zero_CreatesNullPointer()
					{
						var pointer = {{typeName}}.FromIntPtr(nint.Zero);
						Assert.True(pointer.Raw is null);
					}

					[Fact]
					public unsafe void FromUIntPtr_Zero_CreatesNullPointer()
					{
						var pointer = {{typeName}}.FromUIntPtr(nuint.Zero);
						Assert.True(pointer.Raw is null);
					}

				""");
		}

		builder.Append($$"""

				[Fact]
				public unsafe void FromIntPtr_ValidAddress_CreatesPointerWithSameAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromIntPtr((nint)raw);
					Assert.Equal((nint)raw, (nint)pointer.Raw);
				}

				[Fact]
				public unsafe void FromUIntPtr_ValidAddress_CreatesPointerWithSameAddress()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = {{typeName}}.FromUIntPtr((nuint)raw);
					Assert.Equal((nint)raw, (nint)pointer.Raw);
				}

				[Fact]
				public unsafe void ToIntPtr_ReturnsSameAddressAsRaw()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = new {{typeName}}(raw);
					Assert.Equal((nint)raw, pointer.ToIntPtr());
				}

				[Fact]
				public unsafe void ToUIntPtr_ReturnsSameAddressAsRaw()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = new {{typeName}}(raw);
					Assert.Equal((nuint)raw, pointer.ToUIntPtr());
				}

				[Fact]
				public unsafe void ImplicitConversion_FromRawPointer_SetsRaw()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					{{typeName}} pointer = raw;
					Assert.Equal((nint)raw, (nint)pointer.Raw);
				}

				[Fact]
				public unsafe void ExplicitConversion_ToRawPointer_ReturnsRaw()
				{
					using var buffer = new NativeArray<int>(1);
					var raw = {{rawExpr}};
					var pointer = new {{typeName}}(raw);
					var converted = ({{rawType}})pointer;
					Assert.Equal((nint)raw, (nint)converted);
				}
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Declaration.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
