// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GenerateFunctionPointerDeclaration</c>: <c>FromIntPtr</c>/<c>FromUIntPtr</c>
	/// (including the non-<see langword="null"/> guard for non-nullable function pointer types), <c>AsIntPtr</c>/<c>AsUIntPtr</c>,
	/// the <c>Null</c> property for nullable function pointer types, and <c>FromDelegate</c>/<c>ToDelegate</c>.
	/// </summary>
	/// <remarks>
	/// <para>
	/// Untyped function pointer types additionally expose a public <c>Raw</c> property and <c>FromRaw(void*)</c> method (both are
	/// tested here), plus a generic <c>FromDelegate&lt;TDelegate&gt;</c> convenience method that returns the corresponding <em>typed</em>
	/// function pointer type (also tested here). Typed function pointer types, on the other hand, only expose <c>Raw</c> and
	/// <c>FromRaw(TDelegate*)</c> through an explicit <c>IPointer</c> interface implementation, whose public, directly-callable,
	/// delegate-pointer-typed counterparts are meant to be generated by the (not yet implemented) shipped source generator - so those
	/// are intentionally not tested here, per the task instructions.
	/// </para>
	/// </remarks>
	private static void GenerateFunctionPointerDeclarationTests(IncrementalGeneratorPostInitializationContext pic, in FunctionPointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var nonNull = characteristics.Nullability is Nullability.NonNull;
		var typed = characteristics.Typeability is Typeability.Typed;
		var className = $"{SafeName(in characteristics)}_DeclarationTests";

		AppendTestFileHeader(builder, "using System;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void FromIntPtr_ValidAddress_CreatesPointerWithSameAddress()
				{
					var raw = TestFunctionPointerTarget.Raw1;
					var pointer = {{typeName}}.FromIntPtr((nint)raw);
					Assert.Equal((nint)raw, pointer.AsIntPtr);
				}

				[Fact]
				public unsafe void FromUIntPtr_ValidAddress_CreatesPointerWithSameAddress()
				{
					var raw = TestFunctionPointerTarget.Raw1;
					var pointer = {{typeName}}.FromUIntPtr((nuint)raw);
					Assert.Equal((nuint)raw, pointer.AsUIntPtr);
				}

				[Fact]
				public unsafe void AsIntPtr_ReturnsSameAddressAsConstructionArgument()
				{
					var raw = TestFunctionPointerTarget.Raw1;
					var pointer = {{typeName}}.FromIntPtr((nint)raw);
					Assert.Equal((nint)raw, pointer.AsIntPtr);
				}

				[Fact]
				public unsafe void AsUIntPtr_ReturnsSameAddressAsConstructionArgument()
				{
					var raw = TestFunctionPointerTarget.Raw1;
					var pointer = {{typeName}}.FromUIntPtr((nuint)raw);
					Assert.Equal((nuint)raw, pointer.AsUIntPtr);
				}

			""");

		if (nonNull)
		{
			builder.Append($$"""

					[Fact]
					public void FromIntPtr_Zero_ThrowsArgumentNullException()
						=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromIntPtr(nint.Zero));

					[Fact]
					public void FromUIntPtr_Zero_ThrowsArgumentNullException()
						=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromUIntPtr(nuint.Zero));

				""");
		}
		else
		{
			builder.Append($$"""

					[Fact]
					public void Null_Property_ReturnsNullPointer()
					{
						var pointer = {{typeName}}.Null;
						Assert.False(pointer.HasTargetFunction);
						Assert.Equal(nint.Zero, pointer.AsIntPtr);
					}

					[Fact]
					public void FromIntPtr_Zero_CreatesNullPointer()
					{
						var pointer = {{typeName}}.FromIntPtr(nint.Zero);
						Assert.False(pointer.HasTargetFunction);
					}

					[Fact]
					public void FromUIntPtr_Zero_CreatesNullPointer()
					{
						var pointer = {{typeName}}.FromUIntPtr(nuint.Zero);
						Assert.False(pointer.HasTargetFunction);
					}

				""");
		}

		if (typed)
		{
			builder.Append($$"""

					[Fact]
					public unsafe void FromDelegate_ValidDelegate_PointsToSameAddressAsDelegate()
					{
						var pointer = {{typeName}}.FromDelegate(TestFunctionPointerTarget.Delegate1);
						Assert.Equal((nint)TestFunctionPointerTarget.Raw1, pointer.AsIntPtr);
					}

					[Fact]
					public void ToDelegate_ValidPointer_InvokingReturnedDelegateProducesSameResultAsOriginalDelegate()
					{
						var pointer = {{typeName}}.FromDelegate(TestFunctionPointerTarget.Delegate1);
						var roundTripped = pointer.ToDelegate();
						Assert.Equal(TestFunctionPointerTarget.Delegate1(41), roundTripped!(41));
					}

				""");

			if (nonNull)
			{
				builder.Append($$"""

						[Fact]
						public void FromDelegate_NullDelegate_ThrowsArgumentNullException()
							=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromDelegate(null!));

					""");
			}
			else
			{
				builder.Append($$"""

						[Fact]
						public void FromDelegate_NullDelegate_CreatesNullPointer()
						{
							var pointer = {{typeName}}.FromDelegate(null);
							Assert.False(pointer.HasTargetFunction);
						}

						[Fact]
						public void ToDelegate_NullPointer_ReturnsNullDelegate()
						{
							var pointer = {{typeName}}.Null;
							Assert.Null(pointer.ToDelegate());
						}

					""");
			}
		}
		else
		{
			builder.Append($$"""

					[Fact]
					public unsafe void FromRaw_NonNullRawPointer_SetsRaw()
					{
						var raw = TestFunctionPointerTarget.Raw1;
						var pointer = {{typeName}}.FromRaw(raw);
						Assert.Equal((nint)raw, (nint)pointer.Raw);
					}

					[Fact]
					public unsafe void Raw_ReturnsSameAddressAsFromRawArgument()
					{
						var raw = TestFunctionPointerTarget.Raw1;
						var pointer = {{typeName}}.FromRaw(raw);
						Assert.True(pointer.Raw == raw);
					}

					[Fact]
					public unsafe void FromDelegateGeneric_ValidDelegate_ReturnsTypedFunctionPointerWithSameAddress()
					{
						var typedPointer = {{typeName}}.FromDelegate<TestDelegate>(TestFunctionPointerTarget.Delegate1);
						Assert.Equal((nint)TestFunctionPointerTarget.Raw1, typedPointer.AsIntPtr);
					}

				""");

			if (nonNull)
			{
				builder.Append($$"""

						[Fact]
						public unsafe void FromRaw_NullRawPointer_ThrowsArgumentNullException()
							=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromRaw((void*)null));

						[Fact]
						public void FromDelegateGeneric_NullDelegate_ThrowsArgumentNullException()
							=> Assert.Throws<ArgumentNullException>(() => {{typeName}}.FromDelegate<TestDelegate>(null!));

					""");
			}
			else
			{
				builder.Append($$"""

						[Fact]
						public unsafe void FromRaw_NullRawPointer_CreatesNullPointer()
						{
							var pointer = {{typeName}}.FromRaw((void*)null);
							Assert.True(pointer.Raw is null);
							Assert.False(pointer.HasTargetFunction);
						}

						[Fact]
						public unsafe void FromDelegateGeneric_NullDelegate_CreatesNullPointer()
						{
							var typedPointer = {{typeName}}.FromDelegate<TestDelegate>(null);
							Assert.False(typedPointer.HasTargetFunction);
						}

					""");
			}
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Declaration.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
