// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GenerateFunctionPointerNullability</c>: the <c>HasTargetFunction</c> property
	/// (the function pointer equivalent of data pointers' <c>HasTarget</c>), the <c>TryGetNonNull</c> method (for nullable function
	/// pointer types only), and the <see langword="true"/>/<see langword="false"/> operator overloads that allow using a function
	/// pointer directly as a condition (e.g. <c>if (pointer) { ... }</c>).
	/// </summary>
	private static void GenerateFunctionPointerNullabilityTests(IncrementalGeneratorPostInitializationContext pic, in FunctionPointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var nullable = characteristics.Nullability is Nullability.Nullable;
		var className = $"{SafeName(in characteristics)}_NullabilityTests";

		AppendTestFileHeader(builder);

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void HasTargetFunction_NonNullPointer_ReturnsTrue()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					Assert.True(pointer.HasTargetFunction);
				}

				[Fact]
				public unsafe void ConditionalOperators_NonNullPointer_EvaluatesTruthy()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);

					var branchTaken = false;
					if (pointer)
					{
						branchTaken = true;
					}

					Assert.True(branchTaken);

					// Since the compiler requires `operator false` to be defined alongside `operator true` for a type to be
					// usable directly as a boolean condition, successfully compiling and evaluating the `if` above already
					// exercises both operators; this additional if/else pair further confirms the truthy branch is taken.
					var elseBranchTaken = false;
					if (pointer) { } else { elseBranchTaken = true; }
					Assert.False(elseBranchTaken);
				}

			""");

		if (nullable)
		{
			var nonNullCharacteristics = characteristics with { Nullability = Nullability.NonNull };
			var nonNullTypeName = QualifiedTypeName(in nonNullCharacteristics);

			builder.Append($$"""

					[Fact]
					public void HasTargetFunction_NullPointer_ReturnsFalse()
					{
						var pointer = {{typeName}}.FromIntPtr(nint.Zero);
						Assert.False(pointer.HasTargetFunction);
					}

					[Fact]
					public void ConditionalOperators_NullPointer_EvaluatesFalsy()
					{
						var pointer = {{typeName}}.Null;

						var branchTaken = false;
						if (pointer)
						{
							branchTaken = true;
						}

						Assert.False(branchTaken);

						var elseBranchTaken = false;
						if (pointer) { } else { elseBranchTaken = true; }
						Assert.True(elseBranchTaken);
					}

					[Fact]
					public unsafe void TryGetNonNull_NonNullPointer_ReturnsTrueAndSameAddress()
					{
						var raw = TestFunctionPointerTarget.Raw1;
						var pointer = {{typeName}}.FromIntPtr((nint)raw);

						var result = pointer.TryGetNonNull(out {{nonNullTypeName}} nonNullPointer);

						Assert.True(result);
						Assert.Equal((nint)raw, nonNullPointer.AsIntPtr);
					}

					[Fact]
					public void TryGetNonNull_NullPointer_ReturnsFalse()
					{
						var pointer = {{typeName}}.Null;

						var result = pointer.TryGetNonNull(out {{nonNullTypeName}} nonNullPointer);

						Assert.False(result);
						Assert.Equal(nint.Zero, nonNullPointer.AsIntPtr);
					}

				""");
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Nullability.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
