// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;
using Accessibility = SemPtr.SourceGeneration.Accessibility;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GenerateFunctionPointerEquatability</c>: <c>Equals</c> (same type, the
	/// cross-type overload accepting <c>NullableFunctionPointer</c>, and the cross-type overloads accepting the untyped data
	/// pointer types <c>NullablePointerReadOnly</c>/<c>NullablePointerUninitialized</c> - every function pointer type can compare
	/// equal to those, since every function pointer type is convertible to them), <c>GetHashCode</c>, the <c>==</c>/<c>!=</c>
	/// operators (same type and cross-type), and <c>Equals(object?)</c> (only supported for persistent function pointer types;
	/// transient/<see langword="ref"/> <see langword="struct"/> function pointer types always throw
	/// <see cref="System.NotSupportedException"/> from that override, since a <see langword="ref"/> <see langword="struct"/>
	/// cannot be boxed).
	/// </summary>
	private static void GenerateFunctionPointerEquatabilityTests(IncrementalGeneratorPostInitializationContext pic, in FunctionPointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var persistent = characteristics.Persistency is Persistency.Persistent;
		var className = $"{SafeName(in characteristics)}_EquatabilityTests";

		var nfpCharacteristics = new FunctionPointerCharacteristics(Nullability.Nullable, Persistency.Transient, Typeability.Untyped);
		var isNfp = characteristics == nfpCharacteristics;

		var nproCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.ReadOnly, Typeability.Untyped);
		var npuCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.Uninitialized, Typeability.Untyped);
		var nproTypeName = QualifiedTypeName(in nproCharacteristics);
		var npuTypeName = QualifiedTypeName(in npuCharacteristics);

		AppendTestFileHeader(builder, "using System;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void Equals_SameAddress_ReturnsTrue()
				{
					var pointerA = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var pointerB = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					Assert.True(pointerA.Equals(pointerB));
					Assert.True(pointerA == pointerB);
					Assert.False(pointerA != pointerB);
				}

				[Fact]
				public unsafe void Equals_DifferentAddress_ReturnsFalse()
				{
					var pointerA = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var pointerB = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw2);
					Assert.False(pointerA.Equals(pointerB));
					Assert.False(pointerA == pointerB);
					Assert.True(pointerA != pointerB);
				}

				[Fact]
				public unsafe void GetHashCode_EqualPointers_ReturnsSameHashCode()
				{
					var pointerA = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var pointerB = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					Assert.Equal(pointerA.GetHashCode(), pointerB.GetHashCode());
				}

			""");

		if (persistent)
		{
			builder.Append($$"""

					[Fact]
					public unsafe void EqualsObject_SamePointerBoxed_ReturnsTrue()
					{
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						object boxed = pointer;
						Assert.True(pointer.Equals(boxed));
					}

					[Fact]
					public unsafe void EqualsObject_Null_ReturnsFalse()
					{
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						Assert.False(pointer.Equals((object?)null));
					}

					[Fact]
					public unsafe void EqualsObject_UnrelatedType_ReturnsFalse()
					{
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						Assert.False(pointer.Equals("not a pointer"));
					}

				""");
		}
		else
		{
			builder.Append($$"""

					[Fact]
					public unsafe void EqualsObject_AlwaysThrowsNotSupportedException()
					{
						// 'pointer' is a `ref struct` here, so it cannot be captured in a lambda/delegate passed to Assert.Throws;
						// a plain try/catch is used instead.
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						var threw = false;
					#pragma warning disable CS0618 // intentionally testing the obsoleted, unsupported override
						try
						{
							pointer.Equals((object?)null);
						}
						catch (NotSupportedException)
						{
							threw = true;
						}
					#pragma warning restore CS0618
						Assert.True(threw);
					}

				""");
		}

		if (!isNfp)
		{
			var nfpTypeName = QualifiedTypeName(in nfpCharacteristics);

			builder.Append($$"""

					[Fact]
					public unsafe void Equals_NullableFunctionPointer_SameAddress_ReturnsTrue()
					{
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						var other = {{nfpTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						Assert.True(pointer.Equals(other));
						Assert.True(pointer == other);
						Assert.False(pointer != other);
					}

					[Fact]
					public unsafe void Equals_NullableFunctionPointer_DifferentAddress_ReturnsFalse()
					{
						var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
						var other = {{nfpTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw2);
						Assert.False(pointer.Equals(other));
						Assert.False(pointer == other);
						Assert.True(pointer != other);
					}

				""");
		}

		builder.Append($$"""

				[Fact]
				public unsafe void Equals_NullablePointerReadOnly_SameAddress_ReturnsTrue()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var other = {{nproTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					Assert.True(pointer.Equals(other));
					Assert.True(pointer == other);
					Assert.False(pointer != other);
				}

				[Fact]
				public unsafe void Equals_NullablePointerReadOnly_DifferentAddress_ReturnsFalse()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var other = {{nproTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw2);
					Assert.False(pointer.Equals(other));
					Assert.False(pointer == other);
					Assert.True(pointer != other);
				}

				[Fact]
				public unsafe void Equals_NullablePointerUninitialized_SameAddress_ReturnsTrue()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var other = {{npuTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					Assert.True(pointer.Equals(other));
					Assert.True(pointer == other);
					Assert.False(pointer != other);
				}

				[Fact]
				public unsafe void Equals_NullablePointerUninitialized_DifferentAddress_ReturnsFalse()
				{
					var pointer = {{typeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw1);
					var other = {{npuTypeName}}.FromIntPtr((nint)TestFunctionPointerTarget.Raw2);
					Assert.False(pointer.Equals(other));
					Assert.False(pointer == other);
					Assert.True(pointer != other);
				}
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Equatability.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
