// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using Accessibility = SemPtr.SourceGeneration.Accessibility;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerComparability</c>: <c>CompareTo</c> (same type, the cross-type
	/// overloads accepting <c>NullablePointerReadOnly</c>/<c>NullablePointerUninitialized</c>, and <c>CompareTo(object?)</c> for
	/// persistent pointer types), and the <c>&lt;</c>/<c>&gt;</c>/<c>&lt;=</c>/<c>&gt;=</c> operators (same type and cross-type,
	/// in both argument orders). Only generated for sequence pointer types, matching the production generator, which only
	/// implements comparability for pointers into a contiguous sequence of targets.
	/// </summary>
	private static void GenerateComparabilityTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		if (characteristics.Sequencability is not Sequencability.Sequence)
		{
			return;
		}

		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var persistent = characteristics.Persistency is Persistency.Persistent;
		var typed = characteristics.Typeability is Typeability.Typed;
		var rawLow = typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var rawHigh = typed ? "(buffer.Pointer + 1)" : "(void*)((byte*)buffer.Pointer + 1)";
		var className = $"{SafeName(in characteristics)}_ComparabilityTests";

		var nproCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.ReadOnly, Typeability.Untyped);
		var npuCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.Uninitialized, Typeability.Untyped);
		var nproTypeName = QualifiedTypeName(in nproCharacteristics);
		var npuTypeName = QualifiedTypeName(in npuCharacteristics);

		AppendTestFileHeader(builder, "using System;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void CompareTo_SameAddress_ReturnsZero()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerA = new {{typeName}}({{rawLow}});
					var pointerB = new {{typeName}}({{rawLow}});
					Assert.Equal(0, pointerA.CompareTo(pointerB));
					Assert.False(pointerA < pointerB);
					Assert.False(pointerA > pointerB);
					Assert.True(pointerA <= pointerB);
					Assert.True(pointerA >= pointerB);
				}

				[Fact]
				public unsafe void CompareTo_LowerAddress_ReturnsNegative()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerLow = new {{typeName}}({{rawLow}});
					var pointerHigh = new {{typeName}}({{rawHigh}});
					Assert.True(pointerLow.CompareTo(pointerHigh) < 0);
					Assert.True(pointerLow < pointerHigh);
					Assert.False(pointerLow > pointerHigh);
					Assert.True(pointerLow <= pointerHigh);
					Assert.False(pointerLow >= pointerHigh);
				}

				[Fact]
				public unsafe void CompareTo_HigherAddress_ReturnsPositive()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerLow = new {{typeName}}({{rawLow}});
					var pointerHigh = new {{typeName}}({{rawHigh}});
					Assert.True(pointerHigh.CompareTo(pointerLow) > 0);
					Assert.False(pointerHigh < pointerLow);
					Assert.True(pointerHigh > pointerLow);
					Assert.False(pointerHigh <= pointerLow);
					Assert.True(pointerHigh >= pointerLow);
				}

				[Fact]
				public unsafe void CompareTo_NullablePointerReadOnly_ComparesByAddress()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerLow = new {{typeName}}({{rawLow}});
					var other = new {{nproTypeName}}((void*){{rawHigh}});
					Assert.True(pointerLow.CompareTo(other) < 0);
					Assert.True(pointerLow < other);
					Assert.False(pointerLow > other);
					Assert.True(other > pointerLow);
					Assert.False(other < pointerLow);
				}

				[Fact]
				public unsafe void CompareTo_NullablePointerUninitialized_ComparesByAddress()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerLow = new {{typeName}}({{rawLow}});
					var other = new {{npuTypeName}}((void*){{rawHigh}});
					Assert.True(pointerLow.CompareTo(other) < 0);
					Assert.True(pointerLow < other);
					Assert.False(pointerLow > other);
					Assert.True(other > pointerLow);
					Assert.False(other < pointerLow);
				}

			""");

		if (persistent)
		{
			builder.Append($$"""

					[Fact]
					public unsafe void CompareToObject_Null_ReturnsPositive()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawLow}});
						Assert.True(pointer.CompareTo((object?)null) > 0);
					}

					[Fact]
					public unsafe void CompareToObject_SamePointerBoxed_ReturnsZero()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawLow}});
						object boxed = pointer;
						Assert.Equal(0, pointer.CompareTo(boxed));
					}

					[Fact]
					public unsafe void CompareToObject_NonPointer_ThrowsArgumentException()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawLow}});
						Assert.Throws<ArgumentException>(() => pointer.CompareTo("not a pointer"));
					}

				""");
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Comparability.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
