// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using Accessibility = SemPtr.SourceGeneration.Accessibility;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerArithmetic</c>: <c>++</c>/<c>--</c>, addition/subtraction with
	/// <c>nint</c>/<c>nuint</c> offsets (in both argument orders where applicable), and pointer-pointer subtraction yielding the
	/// signed element distance (same type and the cross-type overloads accepting <c>NullablePointerReadOnly</c>/
	/// <c>NullablePointerUninitialized</c>), including the <see langword="checked"/> variant. Only generated for sequence
	/// pointer types with a known element type, matching the production generator.
	/// </summary>
	private static void GenerateArithmeticTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		if (characteristics is not { Sequencability: Sequencability.Sequence, Typeability: Typeability.Typed })
		{
			return;
		}

		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var className = $"{SafeName(in characteristics)}_ArithmeticTests";

		var nproCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.ReadOnly, Typeability.Typed);
		var npuCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.Uninitialized, Typeability.Typed);
		var nproTypeName = QualifiedTypeName(in nproCharacteristics);
		var npuTypeName = QualifiedTypeName(in npuCharacteristics);

		AppendTestFileHeader(builder);

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void IncrementOperator_AdvancesByOneElement()
				{
					using var buffer = new NativeArray<int>(2);
					var pointer = new {{typeName}}(buffer.Pointer);
					var incremented = ++pointer;
					Assert.Equal((nint)(buffer.Pointer + 1), (nint)incremented.Raw);
				}

				[Fact]
				public unsafe void DecrementOperator_RetreatsByOneElement()
				{
					using var buffer = new NativeArray<int>(2);
					var pointer = new {{typeName}}(buffer.Pointer + 1);
					var decremented = --pointer;
					Assert.Equal((nint)buffer.Pointer, (nint)decremented.Raw);
				}

				[Fact]
				public unsafe void AdditionOperator_WithNint_AdvancesByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer);
					var result = pointer + (nint)3;
					Assert.Equal((nint)(buffer.Pointer + 3), (nint)result.Raw);
				}

				[Fact]
				public unsafe void AdditionOperator_WithNuint_AdvancesByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer);
					var result = pointer + (nuint)3;
					Assert.Equal((nint)(buffer.Pointer + 3), (nint)result.Raw);
				}

				[Fact]
				public unsafe void AdditionOperator_NintPlusPointer_AdvancesByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer);
					var result = (nint)3 + pointer;
					Assert.Equal((nint)(buffer.Pointer + 3), (nint)result.Raw);
				}

				[Fact]
				public unsafe void AdditionOperator_NuintPlusPointer_AdvancesByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer);
					var result = (nuint)3 + pointer;
					Assert.Equal((nint)(buffer.Pointer + 3), (nint)result.Raw);
				}

				[Fact]
				public unsafe void SubtractionOperator_WithNint_RetreatsByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer + 3);
					var result = pointer - (nint)3;
					Assert.Equal((nint)buffer.Pointer, (nint)result.Raw);
				}

				[Fact]
				public unsafe void SubtractionOperator_WithNuint_RetreatsByGivenElementCount()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer + 3);
					var result = pointer - (nuint)3;
					Assert.Equal((nint)buffer.Pointer, (nint)result.Raw);
				}

				[Fact]
				public unsafe void SubtractionOperator_SameType_ReturnsSignedElementDistance()
				{
					using var buffer = new NativeArray<int>(4);
					var low = new {{typeName}}(buffer.Pointer);
					var high = new {{typeName}}(buffer.Pointer + 3);
					Assert.Equal(3, high - low);
					Assert.Equal(-3, low - high);
					Assert.Equal(3, checked(high - low));
				}

				[Fact]
				public unsafe void SubtractionOperator_NullablePointerReadOnly_ReturnsSignedElementDistance()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer + 3);
					var other = new {{nproTypeName}}(buffer.Pointer);
					Assert.Equal(3, pointer - other);
					Assert.Equal(-3, other - pointer);
					Assert.Equal(3, checked(pointer - other));
				}

				[Fact]
				public unsafe void SubtractionOperator_NullablePointerUninitialized_ReturnsSignedElementDistance()
				{
					using var buffer = new NativeArray<int>(4);
					var pointer = new {{typeName}}(buffer.Pointer + 3);
					var other = new {{npuTypeName}}(buffer.Pointer);
					Assert.Equal(3, pointer - other);
					Assert.Equal(-3, other - pointer);
					Assert.Equal(3, checked(pointer - other));
				}
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Arithmetic.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
