// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using Accessibility = SemPtr.SourceGeneration.Accessibility;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerAccess</c>: the <c>Target</c> property (mutable for
	/// random-access pointers, read-only for read-only pointers), the sequence indexer, <c>AsSpan</c> (as a member for
	/// persistent pointers, or as an extension method with an identical call site for transient pointers), and, for
	/// uninitialized pointers, <c>InitializeTarget</c>/<c>InitializeTarget(index, ...)</c>/<c>InitializeTargets</c>.
	/// Only generated for non-<see langword="null"/>, typed pointer types, matching the production generator.
	/// </summary>
	private static void GenerateAccessTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		if (characteristics is not { Nullability: Nullability.NonNull, Typeability: Typeability.Typed })
		{
			return;
		}

		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var sequence = characteristics.Sequencability is Sequencability.Sequence;
		var className = $"{SafeName(in characteristics)}_AccessTests";

		AppendTestFileHeader(builder);

		builder.Append($$"""

			public sealed class {{className}}
			{
			""");

		switch (characteristics.Accessibility)
		{
			case Accessibility.Random:
				builder.Append($$"""

						[Fact]
						public unsafe void Target_Get_ReturnsValueAtAddress()
						{
							using var buffer = new NativeArray<int>(1);
							buffer[0] = 42;
							var pointer = {{typeName}}.FromRaw(buffer.Pointer);
							Assert.Equal(42, pointer.Target);
						}

						[Fact]
						public unsafe void Target_Set_WritesValueToAddress()
						{
							using var buffer = new NativeArray<int>(1);
							var pointer = {{typeName}}.FromRaw(buffer.Pointer);
							pointer.Target = 99;
							Assert.Equal(99, buffer[0]);
							Assert.Equal(99, pointer.Target);
						}

					""");

				if (sequence)
				{
					builder.Append($$"""

							[Fact]
							public unsafe void Indexer_NintGet_ReturnsValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								Assert.Equal(2, pointer[(nint)1]);
							}

							[Fact]
							public unsafe void Indexer_NuintGet_ReturnsValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								Assert.Equal(3, pointer[(nuint)2]);
							}

							[Fact]
							public unsafe void Indexer_NintSet_WritesValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								pointer[(nint)1] = 7;
								Assert.Equal(7, buffer[1]);
							}

							[Fact]
							public unsafe void Indexer_NuintSet_WritesValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								pointer[(nuint)2] = 11;
								Assert.Equal(11, buffer[2]);
							}

							[Fact]
							public unsafe void AsSpan_StartAndLength_ReturnsExpectedSlice()
							{
								using var buffer = new NativeArray<int>(4);
								buffer[0] = 10;
								buffer[1] = 20;
								buffer[2] = 30;
								buffer[3] = 40;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan((nint)1, 2);

								Assert.Equal(2, span.Length);
								Assert.Equal(20, span[0]);
								Assert.Equal(30, span[1]);
							}

							[Fact]
							public unsafe void AsSpan_NuintStartAndLength_ReturnsExpectedSlice()
							{
								using var buffer = new NativeArray<int>(4);
								buffer[0] = 10;
								buffer[1] = 20;
								buffer[2] = 30;
								buffer[3] = 40;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan((nuint)1, 2);

								Assert.Equal(2, span.Length);
								Assert.Equal(20, span[0]);
								Assert.Equal(30, span[1]);
							}

							[Fact]
							public unsafe void AsSpan_LengthOnly_ReturnsSliceFromStart()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan(2);

								Assert.Equal(2, span.Length);
								Assert.Equal(1, span[0]);
								Assert.Equal(2, span[1]);
							}

						""");
				}
				break;

			case Accessibility.ReadOnly:
				builder.Append($$"""

						[Fact]
						public unsafe void Target_Get_ReturnsValueAtAddress()
						{
							using var buffer = new NativeArray<int>(1);
							buffer[0] = 123;
							var pointer = {{typeName}}.FromRaw(buffer.Pointer);
							Assert.Equal(123, pointer.Target);
						}

					""");

				if (sequence)
				{
					builder.Append($$"""

							[Fact]
							public unsafe void Indexer_NintGet_ReturnsValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								Assert.Equal(2, pointer[(nint)1]);
							}

							[Fact]
							public unsafe void Indexer_NuintGet_ReturnsValueAtIndex()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);
								Assert.Equal(3, pointer[(nuint)2]);
							}

							[Fact]
							public unsafe void AsSpan_StartAndLength_ReturnsExpectedReadOnlySlice()
							{
								using var buffer = new NativeArray<int>(4);
								buffer[0] = 10;
								buffer[1] = 20;
								buffer[2] = 30;
								buffer[3] = 40;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan((nint)1, 2);

								Assert.Equal(2, span.Length);
								Assert.Equal(20, span[0]);
								Assert.Equal(30, span[1]);
							}

							[Fact]
							public unsafe void AsSpan_NuintStartAndLength_ReturnsExpectedReadOnlySlice()
							{
								using var buffer = new NativeArray<int>(4);
								buffer[0] = 10;
								buffer[1] = 20;
								buffer[2] = 30;
								buffer[3] = 40;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan((nuint)1, 2);

								Assert.Equal(2, span.Length);
								Assert.Equal(20, span[0]);
								Assert.Equal(30, span[1]);
							}

							[Fact]
							public unsafe void AsSpan_LengthOnly_ReturnsSliceFromStart()
							{
								using var buffer = new NativeArray<int>(3);
								buffer[0] = 1;
								buffer[1] = 2;
								buffer[2] = 3;
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var span = pointer.AsSpan(2);

								Assert.Equal(2, span.Length);
								Assert.Equal(1, span[0]);
								Assert.Equal(2, span[1]);
							}

						""");
				}
				break;

			case Accessibility.Uninitialized:
				builder.Append($$"""

						[Fact]
						public unsafe void InitializeTarget_WritesValueAndReturnsRandomAccessPointer()
						{
							using var buffer = new NativeArray<int>(1);
							var pointer = {{typeName}}.FromRaw(buffer.Pointer);

							var initialized = pointer.InitializeTarget(55);

							Assert.Equal(55, buffer[0]);
							Assert.Equal(55, initialized.Target);
							Assert.Equal((nint)buffer.Pointer, (nint)initialized.Raw);
						}

					""");

				if (sequence)
				{
					builder.Append($$"""

							[Fact]
							public unsafe void InitializeTarget_NintIndex_WritesValueAtIndexAndReturnsRandomAccessPointer()
							{
								using var buffer = new NativeArray<int>(3);
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var initialized = pointer.InitializeTarget((nint)1, 7);

								Assert.Equal(7, buffer[1]);
								Assert.Equal((nint)(buffer.Pointer + 1), (nint)initialized.Raw);
							}

							[Fact]
							public unsafe void InitializeTarget_NuintIndex_WritesValueAtIndexAndReturnsRandomAccessPointer()
							{
								using var buffer = new NativeArray<int>(3);
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var initialized = pointer.InitializeTarget((nuint)2, 9);

								Assert.Equal(9, buffer[2]);
								Assert.Equal((nint)(buffer.Pointer + 2), (nint)initialized.Raw);
							}

							[Fact]
							public unsafe void InitializeTargets_WritesAllValuesAndReturnsRandomAccessPointer()
							{
								using var buffer = new NativeArray<int>(3);
								var pointer = {{typeName}}.FromRaw(buffer.Pointer);

								var initialized = pointer.InitializeTargets(new int[] { 4, 5, 6 });

								Assert.Equal(4, buffer[0]);
								Assert.Equal(5, buffer[1]);
								Assert.Equal(6, buffer[2]);
								Assert.Equal((nint)buffer.Pointer, (nint)initialized.Raw);
							}

						""");
				}
				break;
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Access.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
