// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using Accessibility = SemPtr.SourceGeneration.Accessibility;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerEquatability</c>: <c>Equals</c> (same type, and the
	/// cross-type overloads accepting <c>NullablePointerReadOnly</c>/<c>NullablePointerUninitialized</c>), <c>GetHashCode</c>,
	/// the <c>==</c>/<c>!=</c> operators (same type and cross-type), and <c>Equals(object?)</c> (which is only supported for
	/// persistent pointer types; transient/<see langword="ref"/> <see langword="struct"/> pointer types always throw
	/// <see cref="System.NotSupportedException"/> from that override, since a <see langword="ref"/> <see langword="struct"/>
	/// cannot be boxed).
	/// </summary>
	private static void GenerateEquatabilityTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var rawExpr = characteristics.Typeability is Typeability.Typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var persistent = characteristics.Persistency is Persistency.Persistent;
		var className = $"{SafeName(in characteristics)}_EquatabilityTests";

		var nproCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.ReadOnly, Typeability.Untyped);
		var npuCharacteristics = new PointerCharacteristics(Nullability.Nullable, Persistency.Transient, Sequencability.Object, Accessibility.Uninitialized, Typeability.Untyped);
		var isNpro = characteristics == nproCharacteristics;
		var isNpu = characteristics == npuCharacteristics;

		AppendTestFileHeader(builder, "using System;\r\n");

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void Equals_SameAddress_ReturnsTrue()
				{
					using var buffer = new NativeArray<int>(1);
					var pointerA = new {{typeName}}({{rawExpr}});
					var pointerB = new {{typeName}}({{rawExpr}});
					Assert.True(pointerA.Equals(pointerB));
					Assert.True(pointerA == pointerB);
					Assert.False(pointerA != pointerB);
				}

				[Fact]
				public unsafe void Equals_DifferentAddress_ReturnsFalse()
				{
					using var buffer = new NativeArray<int>(2);
					var pointerA = new {{typeName}}({{rawExpr}});
					var pointerB = new {{typeName}}({{(characteristics.Typeability is Typeability.Typed ? "buffer.Pointer + 1" : "(void*)(buffer.Pointer + 1)")}});
					Assert.False(pointerA.Equals(pointerB));
					Assert.False(pointerA == pointerB);
					Assert.True(pointerA != pointerB);
				}

				[Fact]
				public unsafe void GetHashCode_EqualPointers_ReturnsSameHashCode()
				{
					using var buffer = new NativeArray<int>(1);
					var pointerA = new {{typeName}}({{rawExpr}});
					var pointerB = new {{typeName}}({{rawExpr}});
					Assert.Equal(pointerA.GetHashCode(), pointerB.GetHashCode());
				}

			""");

		if (persistent)
		{
			builder.Append($$"""

					[Fact]
					public unsafe void EqualsObject_SamePointerBoxed_ReturnsTrue()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						object boxed = pointer;
						Assert.True(pointer.Equals(boxed));
					}

					[Fact]
					public unsafe void EqualsObject_Null_ReturnsFalse()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						Assert.False(pointer.Equals((object?)null));
					}

					[Fact]
					public unsafe void EqualsObject_UnrelatedType_ReturnsFalse()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						Assert.False(pointer.Equals("not a pointer"));
					}

				""");
		}
		else
		{
			builder.Append($$"""

					[Fact]
					public unsafe void EqualsObject_AlwaysThrowsNotSupportedException()
					{
						// 'pointer' is a `ref struct` here, so it cannot be captured in a lambda/delegate passed to Assert.Throws;
						// a plain try/catch is used instead.
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						var threw = false;
					#pragma warning disable CS0618 // intentionally testing the obsoleted, unsupported override
						try
						{
							pointer.Equals((object?)null);
						}
						catch (NotSupportedException)
						{
							threw = true;
						}
					#pragma warning restore CS0618
						Assert.True(threw);
					}

				""");
		}

		if (!isNpro)
		{
			var nproTypeName = QualifiedTypeName(in nproCharacteristics);

			builder.Append($$"""

					[Fact]
					public unsafe void Equals_NullablePointerReadOnly_SameAddress_ReturnsTrue()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						var other = new {{nproTypeName}}((void*){{rawExpr}});
						Assert.True(pointer.Equals(other));
						Assert.True(pointer == other);
						Assert.False(pointer != other);
					}

					[Fact]
					public unsafe void Equals_NullablePointerReadOnly_DifferentAddress_ReturnsFalse()
					{
						using var buffer = new NativeArray<int>(2);
						var pointer = new {{typeName}}({{rawExpr}});
						var other = new {{nproTypeName}}((void*)(buffer.Pointer + 1));
						Assert.False(pointer.Equals(other));
						Assert.False(pointer == other);
						Assert.True(pointer != other);
					}

				""");
		}

		if (!isNpu)
		{
			var npuTypeName = QualifiedTypeName(in npuCharacteristics);

			builder.Append($$"""

					[Fact]
					public unsafe void Equals_NullablePointerUninitialized_SameAddress_ReturnsTrue()
					{
						using var buffer = new NativeArray<int>(1);
						var pointer = new {{typeName}}({{rawExpr}});
						var other = new {{npuTypeName}}((void*){{rawExpr}});
						Assert.True(pointer.Equals(other));
						Assert.True(pointer == other);
						Assert.False(pointer != other);
					}

					[Fact]
					public unsafe void Equals_NullablePointerUninitialized_DifferentAddress_ReturnsFalse()
					{
						using var buffer = new NativeArray<int>(2);
						var pointer = new {{typeName}}({{rawExpr}});
						var other = new {{npuTypeName}}((void*)(buffer.Pointer + 1));
						Assert.False(pointer.Equals(other));
						Assert.False(pointer == other);
						Assert.True(pointer != other);
					}

				""");
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Equatability.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
