// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerNullability</c>: the <c>HasTarget</c> property, the
	/// <c>TryGetNonNull</c> method (for nullable pointer types only), and the <see langword="true"/>/<see langword="false"/>
	/// operator overloads that allow using a pointer directly as a condition (e.g. <c>if (pointer) { ... }</c>).
	/// </summary>
	private static void GenerateNullabilityTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var typeName = QualifiedTypeName(in characteristics);
		var rawType = RawPointerTypeName(in characteristics);
		var nullable = characteristics.Nullability is Nullability.Nullable;
		var rawExpr = characteristics.Typeability is Typeability.Typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var className = $"{SafeName(in characteristics)}_NullabilityTests";

		AppendTestFileHeader(builder);

		builder.Append($$"""

			public sealed class {{className}}
			{
				[Fact]
				public unsafe void HasTarget_NonNullPointer_ReturnsTrue()
				{
					using var buffer = new NativeArray<int>(1);
					var pointer = new {{typeName}}({{rawExpr}});
					Assert.True(pointer.HasTarget);
				}

				[Fact]
				public unsafe void ConditionalOperators_NonNullPointer_EvaluatesTruthy()
				{
					using var buffer = new NativeArray<int>(1);
					var pointer = new {{typeName}}({{rawExpr}});

					var branchTaken = false;
					if (pointer)
					{
						branchTaken = true;
					}

					Assert.True(branchTaken);

					// Since the compiler requires `operator false` to be defined alongside `operator true` for a type to be
					// usable directly as a boolean condition, successfully compiling and evaluating the `if` above already
					// exercises both operators; this additional if/else pair further confirms the truthy branch is taken.
					var elseBranchTaken = false;
					if (pointer) { } else { elseBranchTaken = true; }
					Assert.False(elseBranchTaken);
				}

			""");

		if (nullable)
		{
			var nonNullCharacteristics = characteristics with { Nullability = Nullability.NonNull };
			var nonNullTypeName = QualifiedTypeName(in nonNullCharacteristics);

			builder.Append($$"""

					[Fact]
					public unsafe void HasTarget_NullPointer_ReturnsFalse()
					{
						var pointer = new {{typeName}}(({{rawType}})null);
						Assert.False(pointer.HasTarget);
					}

					[Fact]
					public unsafe void ConditionalOperators_NullPointer_EvaluatesFalsy()
					{
						var pointer = new {{typeName}}(({{rawType}})null);

						var branchTaken = false;
						if (pointer)
						{
							branchTaken = true;
						}

						Assert.False(branchTaken);

						var elseBranchTaken = false;
						if (pointer) { } else { elseBranchTaken = true; }
						Assert.True(elseBranchTaken);
					}

					[Fact]
					public unsafe void TryGetNonNull_NonNullPointer_ReturnsTrueAndSameAddress()
					{
						using var buffer = new NativeArray<int>(1);
						var raw = {{rawExpr}};
						var pointer = new {{typeName}}(raw);

						var result = pointer.TryGetNonNull(out {{nonNullTypeName}} nonNullPointer);

						Assert.True(result);
						Assert.Equal((nint)raw, (nint)nonNullPointer.Raw);
					}

					[Fact]
					public unsafe void TryGetNonNull_NullPointer_ReturnsFalse()
					{
						var pointer = new {{typeName}}(({{rawType}})null);

						var result = pointer.TryGetNonNull(out {{nonNullTypeName}} nonNullPointer);

						Assert.False(result);
						Assert.True(nonNullPointer.Raw is null);
					}

				""");
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Nullability.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
