// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SemPtr.SourceGeneration;
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

partial class SourceGenerator
{
	/// <summary>
	/// Generates tests mirroring <c>SourceGenerator.GeneratePointerConversions</c>: for every ordered pair of pointer
	/// characteristics for which <see cref="PointerCharacteristics.GetConversion"/> reports a conversion exists, converts an
	/// instance of the "from" pointer type to the "to" pointer type and asserts that the resulting pointer's address is
	/// unchanged. Implicit conversions are exercised via a plain assignment (so that, if the production generator ever mis-classifies
	/// a conversion as implicit when it is really only explicit, the generated test source itself will fail to compile),
	/// while explicit conversions are exercised via an explicit cast. When both the "from" and "to" characteristics are
	/// nullable, an additional test verifies that converting a <see langword="null"/> pointer yields a <see langword="null"/> pointer.
	/// </summary>
	private static void GenerateConversionTests(IncrementalGeneratorPostInitializationContext pic, in PointerCharacteristics characteristics, StringBuilder builder)
	{
		builder.Clear();

		var fromTypeName = QualifiedTypeName(in characteristics);
		var fromRawType = RawPointerTypeName(in characteristics);
		var fromRawExpr = characteristics.Typeability is Typeability.Typed ? "buffer.Pointer" : "(void*)buffer.Pointer";
		var className = $"{SafeName(in characteristics)}_ConversionTests";

		AppendTestFileHeader(builder);

		builder.Append($$"""

			public sealed class {{className}}
			{
			""");

		var testCount = 0;

		foreach (var toCharacteristics in PointerCharacteristics.Enumerate())
		{
			if (characteristics == toCharacteristics)
			{
				continue;
			}

			var conversion = characteristics.GetConversionTo(in toCharacteristics);

			if (conversion is Conversion.None)
			{
				continue;
			}

			var toTypeName = QualifiedTypeName(in toCharacteristics);
			var toSafeName = SafeName(in toCharacteristics);
			var convertExpr = conversion is Conversion.Implicit
				? $"{toTypeName} converted = from;"
				: $"var converted = ({toTypeName})from;";

			builder.Append($$"""

					[Fact]
					public unsafe void To_{{toSafeName}}_PreservesAddress()
					{
						using var buffer = new NativeArray<int>(1);
						var raw = {{fromRawExpr}};
						var from = new {{fromTypeName}}(raw);
						{{convertExpr}}
						Assert.Equal((nint)raw, (nint)converted.Raw);
					}

				""");

			testCount++;

			if (characteristics.Nullability is Nullability.Nullable && toCharacteristics.Nullability is Nullability.Nullable)
			{
				builder.Append($$"""

						[Fact]
						public unsafe void To_{{toSafeName}}_NullPointer_PreservesNull()
						{
							var from = new {{fromTypeName}}(({{fromRawType}})null);
							{{convertExpr}}
							Assert.True(converted.Raw is null);
						}

					""");

				testCount++;
			}
		}

		builder.Append("""
			}
			""");

		AppendTestFileFooter(builder);

		if (testCount is 0)
		{
			// No conversions exist for this pointer type at all (this should not actually happen in practice, since every
			// pointer type at least converts to/from NullablePointerReadOnly and/or NullablePointerUninitialized, but we
			// guard against emitting an otherwise-empty, pointless test class just in case).
			return;
		}

		pic.AddSource($"{TestsNamespace}.{SafeName(in characteristics)}.Conversions.g.cs", SourceText.From(
			text: builder.ToString(),
			encoding: Encoding.UTF8
		));
	}
}
