// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using System.Text;

namespace SemPtr.Tests.SourceGeneration;

/// <summary>
/// Shared naming/emission helpers used by all of the <c>Generate*Tests</c> partial methods.
/// </summary>
/// <remarks>
/// All generated tests are instantiated using <see cref="TestTypeArgument"/> (<c>int</c>) as the concrete type argument for typed
/// pointer types. This keeps the (already enormous) combinatorial test matrix manageable while still exercising every generic
/// code path the source generator emits for the main <c>SemPtr</c> library, since the generated code is not specialized per
/// closed generic type - it is emitted once per <see cref="SemPtr.SourceGeneration.PointerCharacteristics"/> and works identically
/// for any <see langword="unmanaged"/> type argument. A handful of additional, hand-written tests in the main test project
/// exercise a custom user-defined <see langword="unmanaged"/> struct type to prove genericity.
/// </remarks>
partial class SourceGenerator
{
	/// <summary>The disclaimer comment prepended to every generated test source file.</summary>
	private const string Disclaimer = "// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)";

	/// <summary>The concrete type argument used for all generated typed-pointer tests.</summary>
	private const string TestTypeArgument = "int";

	/// <summary>The namespace all generated test classes live in.</summary>
	private const string TestsNamespace = "SemPtr.Tests.Generated";

	/// <summary>Gets the fully-qualified, closed generic (if applicable) type name for the given characteristics, e.g. <c>global::SemPtr.PersistentSequencePointer&lt;int&gt;</c>.</summary>
	private static string QualifiedTypeName(in SemPtr.SourceGeneration.PointerCharacteristics characteristics)
		=> $"global::{SemPtr.SourceGeneration.Config.PointerNamespaceName}.{characteristics.ToTypeName(TestTypeArgument)}";

	/// <summary>Gets the raw pointer C# type (<c>int*</c> or <c>void*</c>) for the given characteristics.</summary>
	private static string RawPointerTypeName(in SemPtr.SourceGeneration.PointerCharacteristics characteristics)
		=> characteristics.Typeability is SemPtr.SourceGeneration.Typeability.Typed ? $"{TestTypeArgument}*" : "void*";

	/// <summary>Gets a unique, identifier-safe name describing the given characteristics, suitable for use in file names, class names and method name fragments.</summary>
	private static string SafeName(in SemPtr.SourceGeneration.PointerCharacteristics characteristics)
		=> characteristics.ToFileNamePrefix(TestTypeArgument);

	/// <summary>Appends the standard file header (disclaimer, nullable-enable, namespace, and imports) shared by all generated test files.</summary>
	private static StringBuilder AppendTestFileHeader(StringBuilder builder, string additionalUsings = "")
		=> builder.Append($$"""
			{{Disclaimer}}
			#nullable enable

			using global::Xunit;
			using global::SemPtr.Tests.Support;
			{{additionalUsings}}

			namespace {{TestsNamespace}};

			""");

	private static StringBuilder AppendTestFileFooter(StringBuilder builder)
		=> builder.Append("""

			#nullable restore
			""");
}
