using Microsoft.CodeAnalysis;
using System.Text;

namespace SemPtr.SourceGeneration;

[Generator(LanguageNames.CSharp)]
internal sealed partial class SourceGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static pic =>
		{
			var builder = new StringBuilder();

			foreach (var characteristics in PointerCharacteristics.Enumerate())
			{
				GeneratePointerDeclaration(pic, in characteristics, builder);
				GeneratePointerAccess(pic, in characteristics, builder);
				GeneratePointerArithmetic(pic, in characteristics, builder);
				GeneratePointerNullability(pic, in characteristics, builder);
				GeneratePointerEquatability(pic, in characteristics, builder);
				GeneratePointerComparability(pic, in characteristics, builder);
				GeneratePointerConversions(pic, in characteristics, builder);
				GeneratePointerFormatting(pic, in characteristics, builder);
				GeneratePointerDebuggerDisplay(pic, in characteristics, builder);
			}

			foreach (var characteristics in FunctionPointerCharacteristics.Enumerate())
			{
				GenerateFunctionPointerDeclaration(pic, in characteristics, builder);
				// No GenerateFunctionPointerAccess: the only "access" function pointers would have is their `Invoke` method, but that's generated by the shipped source generator, because it's dependent on the delegate type argument.
				// No GenerateFunctionPointerArithmetic: function pointers aren't sequencable, so they don't support arithmetic.
				GenerateFunctionPointerNullability(pic, in characteristics, builder);
				GenerateFunctionPointerEquatability(pic, in characteristics, builder);
				// No GenerateFunctionPointerComparability: function pointers aren't sequencable, so they don't provide their own comparability.
				GenerateFunctionPointerConversions(pic, in characteristics, builder);
				GeneratePointerFormatting(pic, in characteristics, builder); // We can reuse the same formatting code as it's written in a generic way that works for both data pointers and function pointers.
				GenerateFunctionPointerDebuggerDisplay(pic, in characteristics, builder);
			}
		});
	}
}
