// This source file was 100% generated by AI (GitHub Copilot)
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using SemPtr.Tests.Support;

namespace SemPtr.AbiTests;

public sealed unsafe class ManagedAbiTests
{
	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
	private static void* Identity(void* value) => value;

	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
	private static void* SelectSecond(void* first, void* second) => second;

	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
	private static void Replace(void** destination, void* replacement) => *destination = replacement;

	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
	private static void WriteInt(int* destination, int value) => *destination = value;

	[Fact]
	public void Identity_RawAndPersistentWrapperSignatures_AreEquivalent()
	{
		using var buffer = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void*, void*>)&Identity;
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer, PersistentPointer>)(void*)raw;
		var pointer = PersistentPointer.FromRaw(buffer.Pointer);

		Assert.Equal((nint)raw(pointer.Raw), (nint)semantic(pointer).Raw);
	}

	[Fact]
	public void Identity_TransientWrapperSignature_PreservesAddress()
	{
		using var buffer = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void*, void*>)&Identity;
		var semantic = (delegate* unmanaged[Cdecl]<Pointer, Pointer>)(void*)raw;
		var pointer = Pointer.FromRaw(buffer.Pointer);

		Assert.Equal((nint)pointer.Raw, (nint)semantic(pointer).Raw);
	}

	[Fact]
	public void NullIdentity_RawAndNullableWrapperSignatures_AreEquivalent()
	{
		var raw = (delegate* unmanaged[Cdecl]<void*, void*>)&Identity;
		var semantic = (delegate* unmanaged[Cdecl]<NullablePersistentPointer, NullablePersistentPointer>)(void*)raw;
		var pointer = NullablePersistentPointer.Null;

		Assert.Equal((nint)raw(null), (nint)semantic(pointer).Raw);
	}

	[Fact]
	public void MultiplePointers_RawAndWrapperSignatures_SelectSameAddress()
	{
		using var firstBuffer = new NativeArray<byte>(1);
		using var secondBuffer = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void*, void*, void*>)&SelectSecond;
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer, PersistentPointer, PersistentPointer>)(void*)raw;
		var first = PersistentPointer.FromRaw(firstBuffer.Pointer);
		var second = PersistentPointer.FromRaw(secondBuffer.Pointer);

		Assert.Equal((nint)raw(first.Raw, second.Raw), (nint)semantic(first, second).Raw);
	}

	[Fact]
	public void PointerToPointer_RawAndWrapperSignatures_MutateSameStorage()
	{
		using var destination = new NativeArray<byte>(1);
		using var replacement = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void**, void*, void>)&Replace;
		var semantic = (delegate* unmanaged[Cdecl]<void**, PersistentPointer, void>)(void*)raw;
		var rawValue = (void*)destination.Pointer;
		var replacementPointer = PersistentPointer.FromRaw(replacement.Pointer);

		raw(&rawValue, (void*)replacement.Pointer);
		semantic(&rawValue, replacementPointer);

		Assert.Equal((nint)rawValue, (nint)replacementPointer.Raw);
	}

	[Fact]
	public void TypedMutation_RawAndWrapperSignatures_WriteSameValue()
	{
		using var buffer = new NativeArray<int>(1);
		var raw = (delegate* unmanaged[Cdecl]<int*, int, void>)&WriteInt;
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer<int>, int, void>)(void*)raw;
		var pointer = PersistentPointer<int>.FromRaw(buffer.Pointer);

		raw(buffer.Pointer, 17);
		semantic(pointer, 42);

		Assert.Equal(42, buffer[0]);
	}
}
