// This source file was 100% generated by AI (GitHub Copilot)
using System;
using SemPtr.Tests.Support;

namespace SemPtr.AbiTests;

public sealed unsafe class NativeAbiTests
{
	[Fact]
	public void Identity_RawAndPersistentWrapperSignatures_AreEquivalent()
	{
		using var buffer = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void*, void*>)NativeAbiLibrary.GetExport("semptr_abi_identity");
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer, PersistentPointer>)NativeAbiLibrary.GetExport("semptr_abi_identity");
		var pointer = PersistentPointer.FromRaw(buffer.Pointer);

		Assert.Equal((nint)raw(pointer.Raw), (nint)semantic(pointer).Raw);
	}

	[Fact]
	public void Identity_TransientWrapperSignature_PreservesAddress()
	{
		using var buffer = new NativeArray<byte>(1);
		var semantic = (delegate* unmanaged[Cdecl]<Pointer, Pointer>)NativeAbiLibrary.GetExport("semptr_abi_identity");
		var pointer = Pointer.FromRaw(buffer.Pointer);

		Assert.Equal((nint)pointer.Raw, (nint)semantic(pointer).Raw);
	}

	[Fact]
	public void NullIdentity_RawAndNullableWrapperSignatures_AreEquivalent()
	{
		var raw = (delegate* unmanaged[Cdecl]<void*, void*>)NativeAbiLibrary.GetExport("semptr_abi_identity");
		var semantic = (delegate* unmanaged[Cdecl]<NullablePersistentPointer, NullablePersistentPointer>)NativeAbiLibrary.GetExport("semptr_abi_identity");

		Assert.Equal((nint)raw(null), (nint)semantic(NullablePersistentPointer.Null).Raw);
	}

	[Fact]
	public void Offset_RawAndTypedWrapperSignatures_AreEquivalent()
	{
		using var buffer = new NativeArray<int>(3);
		var raw = (delegate* unmanaged[Cdecl]<void*, nuint, void*>)NativeAbiLibrary.GetExport("semptr_abi_add_offset");
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer<int>, nuint, PersistentPointer<int>>)NativeAbiLibrary.GetExport("semptr_abi_add_offset");
		var pointer = PersistentPointer<int>.FromRaw(buffer.Pointer);
		var offset = (nuint)(2 * sizeof(int));

		Assert.Equal((nint)raw(pointer.Raw, offset), (nint)semantic(pointer, offset).Raw);
	}

	[Fact]
	public void Replace_RawAndWrapperSignatures_MutateSamePointerStorage()
	{
		using var destination = new NativeArray<byte>(1);
		using var replacement = new NativeArray<byte>(1);
		var raw = (delegate* unmanaged[Cdecl]<void**, void*, void>)NativeAbiLibrary.GetExport("semptr_abi_replace");
		var semantic = (delegate* unmanaged[Cdecl]<void**, PersistentPointer, void>)NativeAbiLibrary.GetExport("semptr_abi_replace");
		var rawValue = (void*)destination.Pointer;
		var replacementPointer = PersistentPointer.FromRaw(replacement.Pointer);

		raw(&rawValue, replacement.Pointer);
		semantic(&rawValue, replacementPointer);

		Assert.Equal((nint)rawValue, (nint)replacementPointer.Raw);
	}

	[Fact]
	public void WriteInt_RawAndTypedWrapperSignatures_WriteSameValue()
	{
		using var buffer = new NativeArray<int>(1);
		var raw = (delegate* unmanaged[Cdecl]<int*, int, void>)NativeAbiLibrary.GetExport("semptr_abi_write_int");
		var semantic = (delegate* unmanaged[Cdecl]<PersistentPointer<int>, int, void>)NativeAbiLibrary.GetExport("semptr_abi_write_int");
		var pointer = PersistentPointer<int>.FromRaw(buffer.Pointer);

		raw(buffer.Pointer, 17);
		semantic(pointer, 42);

		Assert.Equal(42, buffer[0]);
	}
}
