// This source file was 100% generated by AI (GitHub Copilot)
using System;
using System.Runtime.CompilerServices;
using SemPtr.Tests.Support;

namespace SemPtr.Tests;

public sealed class AbiLayoutTests
{
	[Trait("Category", "ABI")]
	[Fact]
	public unsafe void UntypedPersistentWrappers_ArePointerSizedAndBlittable()
	{
		AssertPointerLayout<PersistentPointer>();
		AssertPointerLayout<NullablePersistentPointer>();
		AssertPointerLayout<PersistentSequencePointer>();
		AssertPointerLayout<NullablePersistentSequencePointer>();
		AssertPointerLayout<PersistentPointerReadOnly>();
		AssertPointerLayout<NullablePersistentPointerReadOnly>();
	}

	[Trait("Category", "ABI")]
	[Fact]
	public unsafe void TypedPersistentWrappers_AreTargetPointerSizedAndBlittable()
	{
		AssertTypedPointerLayout<byte>();
		AssertTypedPointerLayout<int>();
		AssertTypedPointerLayout<long>();
		AssertTypedPointerLayout<SampleStruct>();
	}

	[Trait("Category", "ABI")]
	[Fact]
	public unsafe void TransientWrappers_ArePointerSizedAndBlittable()
	{
		Assert.Equal(sizeof(void*), Unsafe.SizeOf<Pointer>());
		Assert.Equal(sizeof(void*), Unsafe.SizeOf<NullablePointer>());
		Assert.Equal(sizeof(void*), Unsafe.SizeOf<Pointer<int>>());
		Assert.Equal(sizeof(void*), Unsafe.SizeOf<NullablePointer<int>>());
		Assert.False(RuntimeHelpers.IsReferenceOrContainsReferences<Pointer>());
		Assert.False(RuntimeHelpers.IsReferenceOrContainsReferences<Pointer<int>>());
	}

	private static unsafe void AssertPointerLayout<T>()
		where T : unmanaged
	{
		Assert.Equal(sizeof(void*), Unsafe.SizeOf<T>());
		Assert.False(RuntimeHelpers.IsReferenceOrContainsReferences<T>());
	}

	private static unsafe void AssertTypedPointerLayout<T>()
		where T : unmanaged
	{
		Assert.Equal(sizeof(T*), Unsafe.SizeOf<PersistentPointer<T>>());
		Assert.Equal(sizeof(T*), Unsafe.SizeOf<NullablePersistentPointer<T>>());
		Assert.False(RuntimeHelpers.IsReferenceOrContainsReferences<PersistentPointer<T>>());
		Assert.False(RuntimeHelpers.IsReferenceOrContainsReferences<NullablePersistentPointer<T>>());
	}
}
