// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using MAI-Code-1.1-Flash)
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using SemPtr;

[assembly: FunctionPointerAttribute<global::SemPtr.Tests.StdCallConventionDelegate>(CallConvs = new[] { typeof(CallConvStdcall) })]

namespace SemPtr.Tests;

[FunctionPointer(CallConvs = new[] { typeof(CallConvCdecl) })]
internal delegate int CdeclConventionDelegate(int value);

internal delegate int StdCallConventionDelegate(int value);

[UnmanagedFunctionPointer(CallingConvention.Winapi)]
internal delegate int WinapiConventionDelegate(int value);

public sealed class FunctionPointerCallingConventionTests
{
	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
	private static int CdeclTarget(int value) => value + 1;

	[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
	private static int StdCallTarget(int value) => value * 2;

	[UnmanagedCallersOnly]
	private static int WinapiTarget(int value) => value + 3;

	[Fact]
	public unsafe void FunctionPointerAttribute_UsesSpecifiedCdeclCallingConvention()
	{
		var pointer = FunctionPointer<CdeclConventionDelegate>.FromRaw((delegate* unmanaged[Cdecl]<int, int>)&CdeclTarget);
		Assert.Equal(43, pointer.Invoke(42));
	}

	[Fact]
	public unsafe void FunctionPointerAttributeTDelegate_UsesSpecifiedStdcallCallingConvention()
	{
		var pointer = FunctionPointer<StdCallConventionDelegate>.FromRaw((delegate* unmanaged[Stdcall]<int, int>)&StdCallTarget);
		Assert.Equal(84, pointer.Invoke(42));
	}

	[Fact]
	public unsafe void UnmanagedFunctionPointerAttribute_UsesSpecifiedWinapiCallingConvention()
	{
		var pointer = FunctionPointer<WinapiConventionDelegate>.FromRaw((delegate* unmanaged<int, int>)&WinapiTarget);
		Assert.Equal(45, pointer.Invoke(42));
	}
}
