// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using SemPtr.Tests.Support;

namespace SemPtr.Tests;

/// <summary>
/// Hand-written tests proving that the pointer types are truly generic and work correctly with custom, user-defined
/// <see langword="unmanaged"/> types, not just built-in primitives like <see cref="int"/> (which is what the generated
/// test suite in <c>SemPtr.Tests.Generated</c> uses for every pointer characteristic combination, to keep the already
/// enormous combinatorial matrix manageable).
/// </summary>
public sealed class GenericityTests
{
	[Fact]
	public unsafe void PersistentPointer_CustomStruct_RoundTripsValue()
	{
		using var buffer = new NativeArray<SampleStruct>(1);
		var value = new SampleStruct { Number = 42, Flag = 7, Ticks = 123456789L };

		var pointer = new PersistentPointer<SampleStruct>(buffer.Pointer) { Target = value };

		Assert.Equal(value, pointer.Target);
		Assert.Equal(value, buffer[0]);
	}

	[Fact]
	public unsafe void PersistentSequencePointer_CustomStruct_IndexerAndSpanRoundTripValues()
	{
		using var buffer = new NativeArray<SampleStruct>(3);
		var values = new[]
		{
			new SampleStruct { Number = 1, Flag = 1, Ticks = 10 },
			new SampleStruct { Number = 2, Flag = 2, Ticks = 20 },
			new SampleStruct { Number = 3, Flag = 3, Ticks = 30 },
		};

		var pointer = new PersistentSequencePointer<SampleStruct>(buffer.Pointer);

		for (var i = 0; i < values.Length; i++)
		{
			pointer[i] = values[i];
		}

		var span = pointer.AsSpan(values.Length);

		Assert.Equal(values.Length, span.Length);
		for (var i = 0; i < values.Length; i++)
		{
			Assert.Equal(values[i], span[i]);
			Assert.Equal(values[i], pointer[i]);
		}
	}

	[Fact]
	public unsafe void PersistentSequencePointerUninitialized_CustomStruct_InitializeTargetsWritesAllValues()
	{
		using var buffer = new NativeArray<SampleStruct>(2);
		var values = new[]
		{
			new SampleStruct { Number = 100, Flag = 1, Ticks = 1000 },
			new SampleStruct { Number = 200, Flag = 0, Ticks = 2000 },
		};

		var pointer = new PersistentSequencePointerUninitialized<SampleStruct>(buffer.Pointer);
		var initialized = pointer.InitializeTargets(values);

		Assert.Equal(values[0], buffer[0]);
		Assert.Equal(values[1], buffer[1]);
		Assert.Equal(values[0], initialized[0]);
		Assert.Equal(values[1], initialized[1]);
	}

	[Fact]
	public unsafe void PersistentPointer_CustomStruct_ArithmeticAndEqualityWorkAcrossElements()
	{
		using var buffer = new NativeArray<SampleStruct>(2);

		var first = new PersistentSequencePointer<SampleStruct>(buffer.Pointer);
		var second = first + 1;

		Assert.NotEqual(first, second);
		Assert.Equal(1, second - first);
		Assert.True(first < second);
		Assert.Equal(first, second - 1);
	}
}
