// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using System;
using SemPtr.Tests.Support;

namespace SemPtr.Tests;

public sealed class RawPointerConversionTests
{
	[Fact]
	public unsafe void PersistentPointer_RawPointerImplicitConversion_PreservesAddress()
	{
		using var buffer = new NativeArray<int>(1);
		int* raw = buffer.Pointer;

		PersistentPointer<int> pointer = raw;

		Assert.Equal((nint)raw, (nint)pointer.Raw);
	}

	[Fact]
	public unsafe void PersistentPointer_SemanticPointerExplicitConversion_PreservesAddress()
	{
		using var buffer = new NativeArray<int>(1);
		int* raw = buffer.Pointer;
		var pointer = PersistentPointer<int>.FromRaw(raw);

		var converted = (int*)pointer;

		Assert.True(converted == raw);
	}

	[Fact]
	public unsafe void PersistentPointer_NullRawPointerImplicitConversion_ThrowsArgumentNullException()
	{
		Assert.Throws<ArgumentNullException>(() => _ = (PersistentPointer<int>)(int*)null);
	}

	[Fact]
	public unsafe void NullablePointerReadOnly_NullRawPointerImplicitConversion_CreatesNullPointer()
	{
		NullablePointerReadOnly<int> pointer = (int*)null;

		Assert.False(pointer.HasTarget);
		Assert.True(pointer.Raw is null);
	}

	[Fact]
	public unsafe void NullablePointerReadOnly_NullSemanticPointerExplicitConversion_ReturnsNull()
	{
		var pointer = NullablePointerReadOnly<int>.FromRaw((int*)null);

		var converted = (int*)pointer;

		Assert.True(converted is null);
	}
}
