<Project>

  <!-- Information shared by all projects -->
  <PropertyGroup>
    
    <!-- Version information, shared by all projects -->
    <VersionPrefix>0.5.0</VersionPrefix>
    <VersionSuffix>alpha.1</VersionSuffix>
    
    <!-- License, copyright, and authorship information -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression> <!-- Technically, this license information is just for the NuGet package, but it is also a good idea to share it as a MSBuild property with all projects. -->
    <Copyright>© 2026 Felix Rüdiger</Copyright>
    <Authors>Felix Rüdiger</Authors>

    <!-- Deterministic build and repository information -->
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/fruediger/SemPtr</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    
  </PropertyGroup>
  
</Project>