<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>SemPtr</PackageId>
    <Description>Semantic Pointers for C#</Description>

    <PackageProjectUrl>https://github.com/fruediger/SemPtr</PackageProjectUrl>
    <PackageTags>semptr;semantic;pointer</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!--<PackageLicenseFile>LICENSE.md</PackageLicenseFile>--> <!-- We already set PackageLicenseExpression in Directory.Build.props, so we don't need to set PackageLicenseFile here, but we will still include the LICENSE.md file in the NuGet package. -->
  </PropertyGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="SemPtr.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemPtr.SourceGeneration\SemPtr.SourceGeneration.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../assets/icon.png" Pack="true" PackagePath="" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../LICENSE.md" Pack="true" PackagePath="" /> <!-- It's always a good idea to include the license file in the NuGet package, even if PackageLicenseExpression is set instead. -->
    <None Include="../SemPtr.FunctionPointerGenerator/bin/$(Configuration)/netstandard2.0/SemPtr.FunctionPointerGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" /> <!-- Don't forget to include the function pointer source generator that we want to ship with the NuGet package. -->
  </ItemGroup>

  <Import Project="..\SemPtr.Common\SemPtr.Common.projitems" Label="Shared" />

</Project>
