// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using System;
using System.Runtime.InteropServices;

namespace SemPtr.Tests.Support;

/// <summary>
/// Provides helpers for allocating zero-initialized, unmanaged (native heap) memory blocks for use as backing storage in pointer tests.
/// </summary>
/// <remarks>
/// Using natively allocated memory (rather than <see langword="fixed"/> stack buffers) allows the resulting pointers to safely be treated
/// as "persistent" for the duration of a test, and avoids any GC-relocation concerns entirely.
/// </remarks>
internal static class NativeBuffer
{
	public static unsafe T* Alloc<T>(int count = 1)
		where T : unmanaged
	{
		if (count <= 0)
		{
			throw new ArgumentOutOfRangeException(nameof(count));
		}

		return (T*)NativeMemory.AllocZeroed((nuint)count, (nuint)sizeof(T));
	}

	public static unsafe void Free(void* pointer) => NativeMemory.Free(pointer);
}

/// <summary>
/// A disposable, RAII-style wrapper around a natively allocated, zero-initialized array of <typeparamref name="T"/> elements.
/// Used as backing storage for constructing and exercising pointer types under test without relying on the managed GC heap.
/// </summary>
internal readonly unsafe struct NativeArray<T> : IDisposable
	where T : unmanaged
{
	public NativeArray(int length)
	{
		Length = length;
		Pointer = NativeBuffer.Alloc<T>(length);
	}

	public int Length { get; }

	public T* Pointer { get; }

	public ref T this[int index]
	{
		get => ref Pointer[index];
	}

	public void Dispose() => NativeBuffer.Free(Pointer);
}
