// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using System;

namespace SemPtr.Tests.Support;

/// <summary>
/// A small, blittable, non-trivial <see langword="unmanaged"/> value type used to prove that pointer types work correctly with
/// custom user-defined unmanaged types, not just built-in primitives like <see cref="int"/>.
/// </summary>
internal struct SampleStruct : IEquatable<SampleStruct>
{
	public int Number;
	public byte Flag;
	public long Ticks;

	public readonly bool Equals(SampleStruct other) => Number == other.Number && Flag == other.Flag && Ticks == other.Ticks;

	public readonly override bool Equals(object? obj) => obj is SampleStruct other && Equals(other);

	public readonly override int GetHashCode() => HashCode.Combine(Number, Flag, Ticks);

	public static bool operator ==(SampleStruct left, SampleStruct right) => left.Equals(right);

	public static bool operator !=(SampleStruct left, SampleStruct right) => !left.Equals(right);
}
