// DISCLAIMER: This source file was 100% generated by AI (GitHub Copilot using Claude Sonnet 5)
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace SemPtr.Tests.Support;

/// <summary>
/// A simple <see langword="delegate"/> type used to exercise typed function pointers (e.g. <c>FunctionPointer&lt;TestDelegate&gt;</c>) in tests.
/// </summary>
[FunctionPointer(CallConvs = new[] { typeof(CallConvThiscall) })]
internal delegate int TestDelegate(int value);

/// <summary>
/// Provides static methods and pre-built <see cref="TestDelegate"/> instances used as target functions for function pointer tests,
/// along with the raw native function pointer addresses obtained from those delegates via <see cref="Marshal.GetFunctionPointerForDelegate(Delegate)"/>.
/// </summary>
/// <remarks>
/// <para>
/// The <see cref="Delegate1"/>/<see cref="Delegate2"/> fields are kept alive for the entire lifetime of the test process (as <see langword="static readonly"/> fields).
/// This is important: the pointer returned by <see cref="Marshal.GetFunctionPointerForDelegate(Delegate)"/> is only guaranteed to remain valid for as long as
/// the delegate instance it was obtained from has not been garbage collected.
/// </para>
/// </remarks>
internal static class TestFunctionPointerTarget
{
	public static int MethodOne(int value) => value + 1;

	public static int MethodTwo(int value) => value * 2;

	public static readonly TestDelegate Delegate1 = MethodOne;

	public static readonly TestDelegate Delegate2 = MethodTwo;

	public static unsafe void* Raw1 => (void*)Marshal.GetFunctionPointerForDelegate(Delegate1);

	public static unsafe void* Raw2 => (void*)Marshal.GetFunctionPointerForDelegate(Delegate2);
}
